In [19]:
import pickle
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split 
from sklearn.model_selection import cross_validate
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix

In [20]:
#Read CSV, index+1 supaya index dimulai dari 1, tidak 0, memudahkan pembacaan dataframe dibawah.
df = pd.read_csv('diabetes.csv')
df.index += 1

In [21]:
#melihat dataframe diabetes.csv
df.head()

preg  plas  pres  skin  test  mass   pedi  age  diabetes
1     6   148    72    35     0  33.6  0.627   50         1
2     1    85    66    29     0  26.6  0.351   31         0
3     8   183    64     0     0  23.3  0.672   32         1
4     1    89    66    23    94  28.1  0.167   21         0
5     0   137    40    35   168  43.1  2.288   33         1

In [22]:
#target / label. Kolom terakhir/kolom 'diabetes'.
#mengambil dataframe untuk disimpan menjadi array. 
#np_target = df.iloc[:,-1:].values #alternatif
np_target = df['diabetes'].values

In [23]:
#Features. Mengambil kolom 1 - 8 dengan mengakses index. 
np_data = df.iloc[:,:-1].values

In [24]:
#KNN
knn_clf = KNeighborsClassifier(n_neighbors = 5)

#Naive bayes
nb_clf = GaussianNB()

In [25]:
#Support Vector Classification model
#clf = svm.SVC(kernel='linear', gamma=0.001, C=100)

In [26]:
#Split dataset, 20% testing 80% training.
X_train, X_test, y_train, y_test = train_test_split(np_data,np_target,test_size=0.2, random_state=None)

In [27]:
X_train

array([[  7.   , 150.   ,  78.   , ...,  35.2  ,   0.692,  54.   ],
       [  0.   , 100.   ,  88.   , ...,  46.8  ,   0.962,  31.   ],
       [  1.   ,  81.   ,  74.   , ...,  46.3  ,   1.096,  32.   ],
       ...,
       [ 11.   ,  85.   ,  74.   , ...,  30.1  ,   0.3  ,  35.   ],
       [  5.   , 166.   ,  72.   , ...,  25.8  ,   0.587,  51.   ],
       [  4.   , 115.   ,  72.   , ...,  28.9  ,   0.376,  46.   ]])

In [28]:
#Cuma buat liat ukuran data train vs data test. imbalance 
len(X_train), len(X_test)

(614, 154)

In [29]:
#Fit model SVM sesuai data training (proses training model)
knn_clf.fit(X_train, y_train)
nb_clf.fit(X_train, y_train)

GaussianNB()

In [30]:
#CrossValidation model yang sudah dibangun. Dengan parameter scoring=accuracy,precision, dan recall
scoring = ['accuracy', 'precision', 'recall']
scores_knn = cross_validate(knn_clf, X_test, y_test, scoring=scoring, cv=5, return_train_score=True)
scores_nb = cross_validate(nb_clf, X_test, y_test, scoring=scoring, cv=5, return_train_score=True)

In [35]:
#Menampilkan hasil dari cross validation. recall yang sangat buruk KNN
knn_score_df = pd.DataFrame.from_dict(scores_knn)
nb_score_df = pd.DataFrame.from_dict(scores_nb)

In [36]:
knn_score_df

fit_time  score_time  test_accuracy  train_accuracy  test_precision  \
0  0.000000    0.002632       0.677419        0.829268        0.600000   
1  0.000997    0.002548       0.548387        0.829268        0.454545   
2  0.000000    0.002997       0.741935        0.796748        0.692308   
3  0.000990    0.001995       0.774194        0.788618        0.750000   
4  0.000998    0.001995       0.833333        0.766129        0.888889   

   train_precision  test_recall  train_recall  
0         0.788462     0.500000      0.803922  
1         0.837209     0.384615      0.720000  
2         0.820513     0.692308      0.640000  
3         0.760870     0.692308      0.700000  
4         0.739130     0.666667      0.666667

In [37]:
nb_score_df

fit_time  score_time  test_accuracy  train_accuracy  test_precision  \
0  0.000997    0.000998       0.774194        0.813008        0.727273   
1  0.000998    0.000997       0.709677        0.821138        0.700000   
2  0.000998    0.000997       0.774194        0.813008        0.714286   
3  0.000997    0.000998       0.806452        0.780488        0.769231   
4  0.000997    0.000998       0.800000        0.806452        0.800000   

   train_precision  test_recall  train_recall  
0         0.818182     0.666667      0.705882  
1         0.791667     0.538462      0.760000  
2         0.800000     0.769231      0.720000  
3         0.755556     0.769231      0.680000  
4         0.813953     0.666667      0.686275

In [15]:
#Hasil cross validation berupa dictionary. Kemudian dictionary disimpan menjadi dataframe. Hanya untuk keperluan pembacaan
df_scores = pd.DataFrame.from_dict(scores)
df_scores.index +=1
df_scores

fit_time  score_time  test_accuracy  train_accuracy  test_precision  \
1  0.001304    0.006226       0.625000        0.778689        0.461538   
2  0.000780    0.002366       0.838710        0.731707        0.800000   
3  0.000882    0.004701       0.741935        0.764228        0.636364   
4  0.000984    0.002193       0.766667        0.782258        0.615385   
5  0.000619    0.002058       0.666667        0.766129        0.500000   

   train_precision  test_recall  train_recall  
1         0.682927     0.545455      0.666667  
2         0.604651     0.727273      0.619048  
3         0.658537     0.636364      0.642857  
4         0.690476     0.800000      0.674419  
5         0.659091     0.200000      0.674419

In [42]:
#DUMP MODEL
pickle.dump(knn_clf, open('model_knn.pkl','wb'))

In [43]:
sample = np.array([6,148,72,35,0,34,1,50])
knn_clf.predict(sample.reshape(1,-1))

array([1], dtype=int64)

In [44]:
knn_clf.predict_proba(sample.reshape(1,-1))

array([[0.4, 0.6]])

In [45]:
y_pred = knn_clf.predict(np_data)
tn, fp, fn, tp = confusion_matrix(np_target, y_pred).ravel()

In [46]:
acc = accuracy_score(np_target, y_pred)
prec= precision_score(np_target, y_pred)
recall = recall_score(np_target, y_pred)

print(acc, prec, recall)

0.7864583333333334 0.7280701754385965 0.6194029850746269
